### ISSUE TITLE
git package dependecy fails

### ISSUE THREAD

**Issue by soerennielsen** [SickChill/qnap-sickchill#6]
I've spent ages searching the net for the Git.qpkg file. 

It's nowhere to be found, but QGit is easily found. In the NAS (SSH) the QGit package actually installs a "git" command (symlinked) so the package seems valid enough. 

Could you please update the dependenvies to require the qgit package instead of the git package?

**Comment by stemo76** [comment]
https://www.dropbox.com/s/fiay536scdscew7/git_2.1.0_x86.qpkg

this is the latest I know of and was working fine till the latest update of my qnap server.

**Comment by soerennielsen** [comment]
Ok, thanks I'll give it a go ☺️

Still, would be easier if you switched it to qgit in the future.

Den 26. apr. 2017 2.28 AM skrev "stemo76" <notifications@github.com>:
